// All possible badges in the achievement system
export const ALL_BADGES = [
  {
    key: "first_analysis",
    name: "Prima Analisi",
    description: "Hai completato la tua prima analisi listing",
    icon: "🔍",
    condition: "Completa la prima analisi del tuo listing",
  },
  {
    key: "wordsmith",
    name: "Wordsmith",
    description: "Hai generato e copiato un titolo ottimizzato",
    icon: "✍️",
    condition: "Genera un titolo con il Title Generator",
  },
  {
    key: "photographer",
    name: "Fotografo",
    description: "Hai analizzato tutte le foto del tuo listing",
    icon: "📸",
    condition: "Analizza le foto con Photo Coach",
  },
  {
    key: "streak_4",
    name: "Costanza",
    description: "4 settimane consecutive di task completati",
    icon: "🔥",
    condition: "Completa tutti i task per 4 settimane di fila",
  },
  {
    key: "streak_8",
    name: "Inarrestabile",
    description: "8 settimane consecutive di task completati",
    icon: "⚡",
    condition: "Completa tutti i task per 8 settimane di fila",
  },
  {
    key: "score_60",
    name: "Sulla Strada Giusta",
    description: "Il tuo listing ha raggiunto score 60+",
    icon: "📈",
    condition: "Raggiungi uno score di 60 o superiore",
  },
  {
    key: "score_80",
    name: "Top Performer",
    description: "Il tuo listing ha raggiunto score 80+",
    icon: "🏆",
    condition: "Raggiungi uno score di 80 o superiore",
  },
  {
    key: "superhost_ready",
    name: "Superhost Ready",
    description: "Il tuo listing soddisfa tutti i criteri Superhost",
    icon: "👑",
    condition: "Soddisfa tutti i criteri per diventare Superhost",
  },
  {
    key: "communicator",
    name: "Comunicatore",
    description: "Hai generato 10+ risposte alle recensioni",
    icon: "💬",
    condition: "Genera almeno 10 risposte alle recensioni",
  },
  {
    key: "analyst",
    name: "Analista",
    description: "Hai completato 3+ analisi del tuo listing",
    icon: "🧠",
    condition: "Completa almeno 3 analisi del listing",
  },
  {
    key: "task_master",
    name: "Task Master",
    description: "Hai completato 20+ task",
    icon: "✅",
    condition: "Completa almeno 20 task in totale",
  },
  {
    key: "perfect_guide",
    name: "Guida Perfetta",
    description: "Hai creato check-in guide + local guide",
    icon: "🗺️",
    condition: "Crea sia la guida check-in che la guida locale",
  },
] as const;
